<?php
/**
 * Language strings for Tshijuka RDP (EN/FR).
 * Language is set automatically from the visitor's browser/phone language (Accept-Language).
 * No switcher: French users see French, English users see English.
 */

$accept = $_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? '';
$lang = 'en';
foreach (array_map('trim', explode(',', $accept)) as $part) {
    $code = strtolower(substr(explode(';', $part)[0], 0, 2));
    if ($code === 'fr' || $code === 'en') {
        $lang = $code;
        break;
    }
}

// Shared background image (same as index): prefer "sign up login background.jpg", fallback to nature image
$bgFile = file_exists(__DIR__ . '/../assets/sign up login background.jpg')
    ? 'sign%20up%20login%20background.jpg'
    : 'nature-7047433_1280.jpg';
$script_path = str_replace('\\', '/', $_SERVER['SCRIPT_NAME'] ?? '');
$in_views = (strpos($script_path, 'views/') !== false);
if ($in_views) {
    $bgImage = '../assets/' . $bgFile;
} else {
    $baseUrl = rtrim(dirname($script_path), '/') . '/';
    $bgImage = $baseUrl . 'assets/' . $bgFile;
}

$strings = [
    'en' => [
        // Index / global
        'about' => 'About',
        'api' => 'API',
        'api_success_desc' => 'The API is available. Use the button below to test the connection.',
        'api_test' => 'Test API',
        'home' => 'Home',
        'problem' => 'The Problem',
        'solution' => 'Our Solution',
        'doc_loss' => 'Lost or inaccessible documents, no trusted way to prove identity or qualifications.',
        'indep_digital' => 'Independent digital credential platform',
        'secure_conn' => 'Secure connection between issuers and document seekers',
        'doc_retrieval' => 'Document retrieval and verification',
        'connect_issuers' => 'Connect with official document issuers',
        'platform_users' => 'Who uses the platform?',
        'users_count' => 'Document Issuers & Document Seekers',
        'doc_issuers' => 'Document Issuers',
        'gov_inst' => 'Government institutions',
        'embassies' => 'Embassies',
        'schools' => 'Institutions',
        'training' => 'Training centers',
        'hospitals' => 'Hospitals',
        'doc_seekers' => 'Document Seekers',
        'displaced' => 'Displaced persons and anyone needing verified documents',
        // Index – problem and solution (full text for landing)
        'index_problem_short' => 'For everyone who possesses important documents — such as educational documents, publications and creative works, and business or commercial documents — keeping them safe is essential because they represent who a person is, what they have achieved, or what they have created.

However, across Africa many people and institutions still lose such documents, particularly in conflict-affected regions. For example, in eastern Democratic Republic of Congo, fighting involving the M23 armed group has disrupted offices and damaged administrative records. In northeast Nigeria, Boko Haram destroyed thousands of schools between 2009 and 2015 (UNESCO), leading to the loss of educational records.

When documents are lost, the common solution is to return to the institution that issued or holds them to request a new copy. Yet this becomes extremely difficult when the institution remains in a conflict area while the person has moved to another region or country. Distance, high costs, and weak communication systems create serious barriers. In addition, many institutions still rely on paper-based records, which can easily be lost, damaged, or destroyed over time.

As a result, document recovery often becomes slow, expensive, or impossible, contributing to a broader challenge across Africa where about 494 million people in Sub-Saharan Africa lack official proof of legal identity (World Bank ID4D, 2021).',
        'index_solution_short' => 'We have created a platform (tshijukardp) that brings together Issuing Institutions and document seekers in one secure digital system. We accompany Institutions in digitizing their records to the cloud, protecting them from permanent loss. At the same time, the platform allows document seekers not only to safely store the documents they already have, but also to recover or retrieve lost documents directly from Issuing Institutions through the web application, from wherever they are, without the need for long-distance travel.',
        // Index – full problem & solution (for newcomers / about page)
        'index_problem_intro' => 'Millions of people lose or cannot access their official documents—certificates, diplomas, IDs—and have no trusted way to prove who they are or what they have achieved.',
        'index_problem_1' => 'Documents lost, destroyed, or left behind due to displacement, disaster, or conflict.',
        'index_problem_2' => 'No single, trusted way to prove identity or qualifications to employers, institutions, or authorities.',
        'index_problem_3' => 'Difficulty reaching or communicating with issuing institutions (embassies, hospitals, etc.), especially from afar.',
        'index_problem_4' => 'Slow, paper-based request processes and long waiting times.',
        'index_problem_5' => 'Risk of fraud, forgery, and lost or unverifiable paper documents.',
        'index_problem_6' => 'Documents scattered across many institutions with no one place to request or store them.',
        'index_problem_7' => 'Displaced persons and refugees unable to retrieve credentials from their country of origin.',
        'index_problem_8' => 'Institutions overwhelmed by manual requests and verification, leading to delays and errors.',
        'index_solution_intro' => 'Tshijuka RDP is a secure platform that connects people who need documents (Document Seekers) with the institutions that issue them (Document Issuers), and gives administrators the tools to oversee the process—including cross-border payments.',
        'index_solution_1' => 'One secure platform where seekers submit requests and issuers manage and fulfill them.',
        'index_solution_2' => 'Real-time status tracking so seekers see when a request is pending, in progress, or completed.',
        'index_solution_3' => 'Pre-loss storage: upload and store copies of important documents before they are lost, for secure backup.',
        'index_solution_4' => 'Tshijuka Pack: one place to view, download, and share your collected documents with consent.',
        'index_solution_5' => 'Secure payments (e.g. Paystack) for document fees; cross-border flow with country agents where needed.',
        'index_solution_6' => 'Direct chat between seeker and issuer (and admissions chat) for questions and updates.',
        'index_solution_7' => 'Issuers can upload documents to the platform in advance and manage requests digitally.',
        'index_solution_8' => 'Admin oversight: user management, document oversight, payment and country-agent management.',
        'index_solution_9' => 'Secure authentication (including MFA), role-based access, and protected document storage and delivery.',
        'login' => 'Log in',
        'join' => 'Join now',
        'footer' => '© Tshijuka RDP. Secure document platform for issuers and seekers.',
        'contact_phone' => '+233591429017',
        'contact_us' => 'Contact us',
        // Login / auth
        'login_title' => 'Log in to your account',
        'check_email' => 'Check your email',
        'code_sent_prefix' => 'Code sent to',
        'email' => 'Email',
        'enter_email' => 'Enter your email',
        'password' => 'Password',
        'enter_password' => 'Enter your password',
        'remember_me' => 'Remember me',
        'forgot_password' => 'Forgot password?',
        'otp_sent' => 'We sent a verification code to your email. Enter it below.',
        'verification_code' => 'Verification code',
        'verify_signin' => 'Verify and sign in',
        'verify' => 'Verify',
        'use_different' => 'Use a different account',
        'cancel_signin' => 'Cancel sign in',
        'dont_have_account' => "Don't have an account?",
        'signup' => 'Sign up',
        'logout' => 'Log out',
        // Signup
        'signup_title' => 'Create your account',
        'full_name' => 'Full name',
        'contact' => 'Contact (phone or address)',
        'confirm_password' => 'Confirm password',
        'select_role' => 'Select your role',
        'role_seeker' => 'Document Seeker',
        'role_issuer' => 'Document Issuing Institutions',
        'create_account' => 'Create account',
        'already_account' => 'Already have an account?',
        // Terms, Privacy & Consent (GDPR / Ghana / Africa)
        'terms_title' => 'Terms of Service',
        'terms_intro' => 'Please read these terms before using the platform.',
        'terms_short' => 'Terms',
        'privacy_title' => 'Privacy Policy',
        'privacy_intro' => 'How we collect, use and protect your data.',
        'privacy_short' => 'Privacy',
        'accept_terms' => 'I have read and accept the',
        'accept_privacy' => 'I have read and accept the',
        'data_protection_note' => '(data protection & GDPR / Ghana compliant).',
        'login_consent' => 'By logging in you agree to our',
        'and' => 'and',
        'back' => 'Back',
        // Password recovery
        'password_recovery' => 'Password recovery',
        'enter_email_recovery' => 'Enter your email to receive reset instructions.',
        'submit' => 'Submit',
        // About page
        'what_we_do' => 'What we do',
        'what_content' => 'We connect document issuers (institutions, embassies) with document seekers so that credentials can be issued, stored, and retrieved securely.',
        'our_vision' => 'Our vision',
        'vision_content' => 'A world where everyone can prove their identity and qualifications through a trusted digital platform.',
        'our_mission' => 'Our mission',
        'mission_content' => 'To provide a secure, independent platform for issuing and recovering official documents.',
        'about_tagline' => 'Secure document retrieval and verification platform connecting issuers and seekers.',
        'about_overview' => 'Tshijuka RDP (Document Retrieval Platform) is an independent digital platform that enables official document issuers—institutions, government bodies, embassies, hospitals, training centers—to connect securely with individuals who need to request, recover, or verify their credentials.',
        'about_who_we_are' => 'We are a dedicated team building technology that restores access to identity and qualifications for people who have lost documents or cannot easily reach issuing institutions. Our platform serves three core roles: Document Seekers (individuals requesting documents), Document Issuers (institutions that issue them), and Administrators (who manage the system and, where applicable, cross-border payments and agents).',
        'about_what_we_do_full' => 'We provide a single, secure environment where document requests are submitted, tracked, and fulfilled; where seekers can store copies of documents before loss (pre-loss storage) and access their Tshijuka Pack; and where issuers can manage requests, update status, and deliver documents digitally. We also support secure payments and, in cross-border scenarios, a clear flow from payment receipt to agent payout and institution compensation.',
        'about_who_we_serve' => 'We serve Document Seekers (including displaced persons, students, and professionals) who need to obtain or prove their credentials; Document Issuers (institutions, embassies, government offices, hospitals, training centers) who want to digitize and streamline issuance and recovery; and Administrators who need visibility and control over users, documents, and payments.',
        'about_platform_highlights' => 'Platform highlights',
        'about_highlight_1' => 'Secure request and delivery of official documents with status tracking and digital storage.',
        'about_highlight_2' => 'Pre-loss document storage so users keep a backup before originals are lost or damaged.',
        'about_highlight_3' => 'Tshijuka Pack for viewing, downloading, and sharing collected documents with consent.',
        'about_highlight_4' => 'Integrated payments and, where applicable, cross-border agent flow for institution payout.',
        'about_highlight_5' => 'Chat between seekers and issuers; admissions chat for related communications.',
        'about_contact_professional' => 'For partnership, support, or general inquiries, reach out to our team.',
        'about_who_we_are_heading' => 'Who we are',
        'about_what_we_provide_heading' => 'What we provide',
        'about_who_we_serve_heading' => 'Who we serve',
        'services_users' => 'Services by user type',
        'for_issuers' => 'For Document Issuers',
        'for_issuers_content' => 'Issue and manage digital credentials with security and ease.',
        'secure_guidance' => 'Secure issuance and guidance',
        'secure_guidance_content' => 'We guide you through secure setup and best practices.',
        'benefits_digital' => 'Benefits of going digital',
        'benefit1' => 'Reduced loss and fraud',
        'benefit2' => 'Faster verification',
        'benefit3' => 'Better record-keeping',
        'benefit4' => 'Easier recovery for users',
        'benefit5' => 'Compliance and audit trail',
        'contact_digital' => 'Contact us to go digital',
        'for_seekers' => 'For Document Seekers',
        'doc_recovery_services' => 'Document recovery services',
        'doc_recovery_content' => 'Request and recover your documents from registered issuers.',
        'services_for_seekers' => 'What we offer',
        'contact_recovery' => 'Contact for recovery support',
        'footer_connecting' => 'Connecting issuers and seekers for secure document exchange.',
        'about_lead' => 'We bridge document issuers and seekers so credentials can be issued, stored, and recovered securely.',
        'issuer_guide_intro' => 'Our team will guide you through:',
        'seeker_help_intro' => 'How we help you:',
        'footer_contact' => 'Contact Tshijuka RDP',
        // MFA setup / verify
        'email_verification_title' => 'Email verification',
        'email_verification_desc' => 'Add an extra layer of security by verifying your email with a code.',
        'email_on' => 'Email verification is on.',
        'email_on_desc' => 'Your account is protected with one-time codes sent to your email.',
        'back_dashboard' => 'Back to dashboard',
        'when_enabled' => 'When enabled, you will receive a code by email when signing in.',
        'send_code' => 'Send verification code',
        'enter_code_sent' => 'Enter the code sent to',
        'code' => 'Code',
        'turn_on' => 'Turn on',
        'send_new' => 'Send new code',
        'done' => 'Done.',
        'done_desc' => 'Email verification is now enabled for your account.',
        // Student dashboard / recovery tools
        'clear_all' => 'Clear all',
        'recovery_tools' => 'Recovery tools',
        'recovery_subtitle' => 'Submit requests, view your Tshijuka Pack, and track progress.',
        'submit_request' => 'Submit a request',
        'submit_desc' => 'Request documents from issuers.',
        'submit_feat1' => 'Submit new document requests',
        'submit_feat2' => 'Track status of requests',
        'submit_feat3' => 'Receive updates from issuers',
        'submit_feat4' => 'Secure and private',
        'submit_new' => 'Submit new request',
        'tshijuka_pack' => 'Tshijuka Pack',
        'tshijuka_desc' => 'Your collected documents in one place.',
        'tshijuka_feat1' => 'View all your documents',
        'tshijuka_feat2' => 'Download when needed',
        'tshijuka_feat3' => 'Share with consent',
        'tshijuka_feat4' => 'Always available',
        'view_docs' => 'View documents',
        'track_progress' => 'Track progress',
        'track_desc' => 'Check the status of your document requests.',
        'track_feat1' => 'Enter your document ID',
        'track_feat2' => 'See current status',
        'track_feat3' => 'View issuer updates',
        'track_feat4' => 'Get notified when ready',
        'track_btn' => 'Check status',
        'check_status' => 'Check status',
        // Preloss (store documents before loss) – dashboard card + page
        'preloss_title' => 'Upload & protect your documents',
        'preloss_desc' => 'Upload and store copies of your important documents here. If you ever lose the originals, you will have a secure backup.',
        'preloss_feat1' => 'Upload certificates, IDs, diplomas and other documents',
        'preloss_feat2' => 'Keep a secure backup before any loss or damage',
        'preloss_feat3' => 'Download your documents whenever you need them',
        'preloss_feat4' => 'Your files are stored securely and privately',
        'preloss_btn' => 'Upload & protect my documents',
        'preloss_lead' => 'Upload and store copies of your important documents here. If you ever lose the originals, you will have a secure backup.',
        'preloss_page_title' => 'Store documents (pre-loss)',
        'preloss_upload' => 'Upload a document',
        'preloss_doc_title' => 'Document title',
        'preloss_doc_title_placeholder' => 'e.g. Birth certificate, Academic diploma',
        'preloss_choose_file' => 'Choose file',
        'preloss_upload_btn' => 'Upload',
        'preloss_list' => 'Your stored documents',
        'preloss_empty' => 'No documents stored yet. Upload documents above to keep a copy before any loss.',
        'preloss_uploaded_on' => 'Uploaded on',
        'preloss_download' => 'Download',
        'preloss_delete' => 'Delete',
        'preloss_delete_confirm' => 'Delete this document? This cannot be undone.',
        'preloss_docs_to_upload' => 'Documents to upload',
        'preloss_add_another' => 'Add another document',
        'preloss_multi_hint' => 'Add one or more documents. You can upload several files at once or take a picture.',
        'preloss_multiple_hint' => 'Select one or more files',
        'preloss_take_picture' => 'Take picture',
        'preloss_remove' => 'Remove',
        // 404
        'page_not_found' => 'Page Not Found',
        'page_not_found_desc' => 'This page does not exist. Sorry, the page you are looking for could not be found. It was not intentional.',
        'back_home' => 'Back to Home',
    ],
    'fr' => [
        // Index / global
        'about' => 'À propos',
        'api' => 'API',
        'api_success_desc' => 'L\'API est disponible. Utilisez le bouton ci-dessous pour tester la connexion.',
        'api_test' => 'Tester l\'API',
        'home' => 'Accueil',
        'problem' => 'Le problème',
        'solution' => 'Notre solution',
        'doc_loss' => 'Documents perdus ou inaccessibles, pas de moyen fiable de prouver son identité ou ses qualifications.',
        'indep_digital' => 'Plateforme indépendante de titres numériques',
        'secure_conn' => 'Connexion sécurisée entre émetteurs et demandeurs de documents',
        'doc_retrieval' => 'Récupération et vérification des documents',
        'connect_issuers' => 'Se connecter aux émetteurs officiels de documents',
        'platform_users' => 'Qui utilise la plateforme ?',
        'users_count' => 'Émetteurs de documents & Demandeurs de documents',
        'doc_issuers' => 'Émetteurs de documents',
        'gov_inst' => 'Institutions gouvernementales',
        'embassies' => 'Ambassades',
        'schools' => 'Institutions',
        'training' => 'Centres de formation',
        'hospitals' => 'Hôpitaux',
        'doc_seekers' => 'Demandeurs de documents',
        'displaced' => 'Personnes déplacées et toute personne ayant besoin de documents vérifiés',
        'index_problem_short' => 'Les documents sont perdus ou détruits ; beaucoup ne peuvent prouver leur identité ou leurs qualifications. Joindre institutions, ambassades ou hôpitaux est difficile, et les processus sur papier sont lents et exposés à la fraude.',
        'index_solution_short' => 'Une plateforme sécurisée : les demandeurs font des demandes, les émetteurs les traitent, les administrateurs supervisent. Suivi en temps réel, stockage avant perte, accès à vos documents en un lieu (Tshijuka Pack). Paiements et chat sécurisés.',
        'index_problem_intro' => 'Des millions de personnes perdent ou n\'ont pas accès à leurs documents officiels—certificats, diplômes, pièces d\'identité—et n\'ont aucun moyen fiable de prouver qui elles sont ou ce qu\'elles ont accompli.',
        'index_problem_1' => 'Documents perdus, détruits ou laissés derrière (déplacement, catastrophe, conflit).',
        'index_problem_2' => 'Aucun moyen unique et fiable de prouver son identité ou ses qualifications auprès des employeurs, établissements ou autorités.',
        'index_problem_3' => 'Difficulté à joindre ou communiquer avec les institutions émettrices (ambassades, hôpitaux, etc.), surtout à distance.',
        'index_problem_4' => 'Processus de demande lents, sur papier, et longs délais d\'attente.',
        'index_problem_5' => 'Risque de fraude, falsification et documents papier perdus ou non vérifiables.',
        'index_problem_6' => 'Documents dispersés dans de nombreuses institutions sans lieu unique pour les demander ou les stocker.',
        'index_problem_7' => 'Personnes déplacées et réfugiés incapables de récupérer leurs titres dans leur pays d\'origine.',
        'index_problem_8' => 'Institutions débordées par les demandes et vérifications manuelles, entraînant retards et erreurs.',
        'index_solution_intro' => 'Tshijuka RDP est une plateforme sécurisée qui connecte les personnes qui ont besoin de documents (Demandeurs) aux institutions qui les émettent (Émetteurs), et donne aux administrateurs les outils pour superviser le processus—y compris les paiements transfrontaliers.',
        'index_solution_1' => 'Une plateforme sécurisée où les demandeurs soumettent des demandes et les émetteurs les gèrent et les traitent.',
        'index_solution_2' => 'Suivi en temps réel du statut pour que les demandeurs voient si une demande est en attente, en cours ou terminée.',
        'index_solution_3' => 'Stockage pré-perte : téléverser et stocker des copies de documents importants avant qu\'ils ne soient perdus.',
        'index_solution_4' => 'Tshijuka Pack : un seul endroit pour voir, télécharger et partager vos documents collectés, avec consentement.',
        'index_solution_5' => 'Paiements sécurisés (ex. Paystack) pour les frais de documents ; flux transfrontaliers avec agents par pays si besoin.',
        'index_solution_6' => 'Chat direct entre demandeur et émetteur (et chat admissions) pour questions et mises à jour.',
        'index_solution_7' => 'Les émetteurs peuvent téléverser des documents à l\'avance et gérer les demandes numériquement.',
        'index_solution_8' => 'Supervision admin : gestion des utilisateurs, des documents, des paiements et des agents par pays.',
        'index_solution_9' => 'Authentification sécurisée (dont MFA), accès par rôle, stockage et livraison de documents protégés.',
        'login' => 'Connexion',
        'join' => 'Rejoindre',
        'footer' => '© Tshijuka RDP. Plateforme sécurisée de documents pour émetteurs et demandeurs.',
        'contact_phone' => '+233591429017',
        'contact_us' => 'Nous contacter',
        // Login / auth
        'login_title' => 'Connectez-vous à votre compte',
        'check_email' => 'Vérifiez votre e-mail',
        'code_sent_prefix' => 'Code envoyé à',
        'email' => 'E-mail',
        'enter_email' => 'Entrez votre e-mail',
        'password' => 'Mot de passe',
        'enter_password' => 'Entrez votre mot de passe',
        'remember_me' => 'Se souvenir de moi',
        'forgot_password' => 'Mot de passe oublié ?',
        'otp_sent' => 'Nous avons envoyé un code de vérification à votre e-mail. Entrez-le ci-dessous.',
        'verification_code' => 'Code de vérification',
        'verify_signin' => 'Vérifier et se connecter',
        'verify' => 'Vérifier',
        'use_different' => 'Utiliser un autre compte',
        'cancel_signin' => 'Annuler la connexion',
        'dont_have_account' => "Vous n'avez pas de compte ?",
        'signup' => 'S\'inscrire',
        'logout' => 'Déconnexion',
        // Signup
        'signup_title' => 'Créez votre compte',
        'full_name' => 'Nom complet',
        'contact' => 'Contact (téléphone ou adresse)',
        'confirm_password' => 'Confirmer le mot de passe',
        'select_role' => 'Choisissez votre rôle',
        'role_seeker' => 'Demandeur de documents',
        'role_issuer' => 'Institutions d\'émission de documents',
        'create_account' => 'Créer le compte',
        'already_account' => 'Vous avez déjà un compte ?',
        // Terms, Privacy & Consent (GDPR / Ghana / Africa)
        'terms_title' => 'Conditions d\'utilisation',
        'terms_intro' => 'Veuillez lire ces conditions avant d\'utiliser la plateforme.',
        'terms_short' => 'Conditions',
        'privacy_title' => 'Politique de confidentialité',
        'privacy_intro' => 'Comment nous collectons, utilisons et protégeons vos données.',
        'privacy_short' => 'Confidentialité',
        'accept_terms' => 'J\'ai lu et j\'accepte les',
        'accept_privacy' => 'J\'ai lu et j\'accepte la',
        'data_protection_note' => '(protection des données et conformité RGPD / Ghana).',
        'login_consent' => 'En vous connectant vous acceptez nos',
        'and' => 'et',
        'back' => 'Retour',
        // Password recovery
        'password_recovery' => 'Récupération du mot de passe',
        'enter_email_recovery' => 'Entrez votre e-mail pour recevoir les instructions de réinitialisation.',
        'submit' => 'Envoyer',
        // About page
        'what_we_do' => 'Ce que nous faisons',
        'what_content' => 'Nous connectons les émetteurs de documents (institutions, ambassades) et les demandeurs pour que les titres soient émis, stockés et récupérés en toute sécurité.',
        'our_vision' => 'Notre vision',
        'vision_content' => 'Un monde où chacun peut prouver son identité et ses qualifications via une plateforme numérique de confiance.',
        'our_mission' => 'Notre mission',
        'mission_content' => 'Offrir une plateforme sécurisée et indépendante pour l\'émission et la récupération de documents officiels.',
        'about_tagline' => 'Plateforme sécurisée de récupération et vérification de documents, connectant émetteurs et demandeurs.',
        'about_overview' => 'Tshijuka RDP (Plateforme de Récupération de Documents) est une plateforme numérique indépendante qui permet aux émetteurs officiels—institutions, organismes publics, ambassades, hôpitaux, centres de formation—de se connecter de façon sécurisée avec les personnes qui ont besoin de demander, récupérer ou vérifier leurs titres.',
        'about_who_we_are' => 'Nous sommes une équipe dédiée qui conçoit une technologie pour restaurer l\'accès à l\'identité et aux qualifications des personnes ayant perdu leurs documents ou ne pouvant pas facilement joindre les institutions émettrices. Notre plateforme sert trois rôles : Demandeurs de documents, Émetteurs de documents et Administrateurs (gestion du système et, le cas échéant, paiements transfrontaliers et agents).',
        'about_what_we_do_full' => 'Nous offrons un environnement unique et sécurisé où les demandes sont soumises, suivies et traitées ; où les demandeurs peuvent stocker des copies avant perte et accéder à leur Tshijuka Pack ; et où les émetteurs gèrent les demandes, mettent à jour le statut et livrent les documents numériquement. Nous prenons aussi en charge les paiements sécurisés et, en contexte transfrontalien, un flux clair du paiement reçu jusqu\'à la compensation de l\'agent et de l\'institution.',
        'about_who_we_serve' => 'Nous servons les Demandeurs de documents (dont personnes déplacées, étudiants, professionnels), les Émetteurs (institutions, ambassades, bureaux gouvernementaux, hôpitaux, centres de formation) qui souhaitent numériser et simplifier l\'émission et la récupération, et les Administrateurs qui ont besoin de visibilité et de contrôle sur les utilisateurs, documents et paiements.',
        'about_platform_highlights' => 'Points forts de la plateforme',
        'about_highlight_1' => 'Demande et livraison sécurisées de documents officiels avec suivi de statut et stockage numérique.',
        'about_highlight_2' => 'Stockage pré-perte pour que les utilisateurs gardent une sauvegarde avant perte ou dommage des originaux.',
        'about_highlight_3' => 'Tshijuka Pack pour voir, télécharger et partager les documents collectés, avec consentement.',
        'about_highlight_4' => 'Paiements intégrés et, le cas échéant, flux d\'agents transfrontaliers pour le versement aux institutions.',
        'about_highlight_5' => 'Chat entre demandeurs et émetteurs ; chat admissions pour les communications associées.',
        'about_contact_professional' => 'Pour partenariat, support ou demandes générales, contactez notre équipe.',
        'about_who_we_are_heading' => 'Qui nous sommes',
        'about_what_we_provide_heading' => 'Ce que nous offrons',
        'about_who_we_serve_heading' => 'Qui nous servons',
        'services_users' => 'Services par type d\'utilisateur',
        'for_issuers' => 'Pour les émetteurs de documents',
        'for_issuers_content' => 'Émettez et gérez les titres numériques en toute sécurité.',
        'secure_guidance' => 'Émission sécurisée et accompagnement',
        'secure_guidance_content' => 'Nous vous accompagnons pour une mise en place sécurisée et les bonnes pratiques.',
        'benefits_digital' => 'Avantages du passage au numérique',
        'benefit1' => 'Moins de perte et de fraude',
        'benefit2' => 'Vérification plus rapide',
        'benefit3' => 'Meilleure tenue des dossiers',
        'benefit4' => 'Récupération plus facile pour les utilisateurs',
        'benefit5' => 'Conformité et traçabilité',
        'contact_digital' => 'Contactez-nous pour passer au numérique',
        'for_seekers' => 'Pour les demandeurs de documents',
        'doc_recovery_services' => 'Services de récupération de documents',
        'doc_recovery_content' => 'Demandez et récupérez vos documents auprès des émetteurs enregistrés.',
        'services_for_seekers' => 'Ce que nous proposons',
        'contact_recovery' => 'Contact pour le support récupération',
        'footer_connecting' => 'Connecter émetteurs et demandeurs pour un échange sécurisé de documents.',
        'about_lead' => 'Nous mettons en relation émetteurs et demandeurs de documents pour que les titres soient émis, stockés et récupérés en toute sécurité.',
        'issuer_guide_intro' => 'Notre équipe vous accompagne pour :',
        'seeker_help_intro' => 'Comment nous vous aidons :',
        'footer_contact' => 'Contacter Tshijuka RDP',
        // MFA setup / verify
        'email_verification_title' => 'Vérification par e-mail',
        'email_verification_desc' => 'Ajoutez une couche de sécurité en vérifiant votre e-mail avec un code.',
        'email_on' => 'La vérification par e-mail est activée.',
        'email_on_desc' => 'Votre compte est protégé par des codes à usage unique envoyés à votre e-mail.',
        'back_dashboard' => 'Retour au tableau de bord',
        'when_enabled' => 'Une fois activée, vous recevrez un code par e-mail à chaque connexion.',
        'send_code' => 'Envoyer le code de vérification',
        'enter_code_sent' => 'Entrez le code envoyé à',
        'code' => 'Code',
        'turn_on' => 'Activer',
        'send_new' => 'Envoyer un nouveau code',
        'done' => 'Terminé.',
        'done_desc' => 'La vérification par e-mail est maintenant activée pour votre compte.',
        // Student dashboard / recovery tools
        'clear_all' => 'Tout effacer',
        'recovery_tools' => 'Outils de récupération',
        'recovery_subtitle' => 'Soumettez des demandes, consultez votre Tshijuka Pack et suivez l\'avancement.',
        'submit_request' => 'Soumettre une demande',
        'submit_desc' => 'Demander des documents aux émetteurs.',
        'submit_feat1' => 'Soumettre de nouvelles demandes de documents',
        'submit_feat2' => 'Suivre le statut des demandes',
        'submit_feat3' => 'Recevoir des mises à jour des émetteurs',
        'submit_feat4' => 'Sécurisé et confidentiel',
        'submit_new' => 'Nouvelle demande',
        'tshijuka_pack' => 'Tshijuka Pack',
        'tshijuka_desc' => 'Vos documents regroupés en un seul endroit.',
        'tshijuka_feat1' => 'Voir tous vos documents',
        'tshijuka_feat2' => 'Télécharger quand nécessaire',
        'tshijuka_feat3' => 'Partager avec consentement',
        'tshijuka_feat4' => 'Toujours disponible',
        'view_docs' => 'Voir les documents',
        'track_progress' => 'Suivre l\'avancement',
        'track_desc' => 'Vérifiez le statut de vos demandes de documents.',
        'track_feat1' => 'Entrez l\'ID de votre document',
        'track_feat2' => 'Voir le statut actuel',
        'track_feat3' => 'Voir les mises à jour des émetteurs',
        'track_feat4' => 'Être notifié quand c\'est prêt',
        'track_btn' => 'Vérifier le statut',
        'check_status' => 'Vérifier le statut',
        // Preloss (store documents before loss) – dashboard card + page
        'preloss_title' => 'Téléverser et protéger vos documents',
        'preloss_desc' => 'Téléversez et conservez ici des copies de vos documents importants. En cas de perte des originaux, vous disposerez d\'une sauvegarde sécurisée.',
        'preloss_feat1' => 'Téléverser certificats, pièces d\'identité, diplômes et autres documents',
        'preloss_feat2' => 'Garder une copie de sauvegarde avant toute perte ou dommage',
        'preloss_feat3' => 'Télécharger vos documents quand vous en avez besoin',
        'preloss_feat4' => 'Vos fichiers sont stockés de façon sécurisée et privée',
        'preloss_btn' => 'Téléverser et protéger mes documents',
        'preloss_lead' => 'Téléversez et conservez ici des copies de vos documents importants. En cas de perte des originaux, vous disposerez d\'une sauvegarde sécurisée.',
        'preloss_page_title' => 'Stocker des documents (avant perte)',
        'preloss_upload' => 'Téléverser un document',
        'preloss_doc_title' => 'Titre du document',
        'preloss_doc_title_placeholder' => 'ex. Acte de naissance, Diplôme',
        'preloss_choose_file' => 'Choisir un fichier',
        'preloss_upload_btn' => 'Téléverser',
        'preloss_list' => 'Vos documents stockés',
        'preloss_empty' => 'Aucun document stocké. Téléversez des documents ci-dessus pour en garder une copie avant toute perte.',
        'preloss_uploaded_on' => 'Téléversé le',
        'preloss_download' => 'Télécharger',
        'preloss_delete' => 'Supprimer',
        'preloss_delete_confirm' => 'Supprimer ce document ? Cette action est irréversible.',
        'preloss_docs_to_upload' => 'Documents à téléverser',
        'preloss_add_another' => 'Ajouter un autre document',
        'preloss_multi_hint' => 'Ajoutez un ou plusieurs documents. Vous pouvez téléverser plusieurs fichiers à la fois ou prendre une photo.',
        'preloss_multiple_hint' => 'Sélectionner un ou plusieurs fichiers',
        'preloss_take_picture' => 'Prendre une photo',
        'preloss_remove' => 'Supprimer',
        // 404
        'page_not_found' => 'Page introuvable',
        'page_not_found_desc' => 'Cette page n\'existe pas. Désolé, la page que vous recherchez est introuvable. Ce n\'était pas intentionnel.',
        'back_home' => 'Retour à l\'accueil',
    ],
];

$L = isset($strings[$lang]) ? $strings[$lang] : $strings['en'];

// Fallback: ensure missing keys never break the page (e.g. after deployment)
if (!function_exists('lang_get')) {
    function lang_get($key, $fallback = '') {
        global $L;
        return isset($L[$key]) ? $L[$key] : $fallback;
    }
}
